import { Chapter } from "../routes/video";

export const getChaptersFromJson = (json: any) => {
  let chapters: Chapter[] = [];
  let contents;

  const panels = json.engagementPanels;
  for (let panel of panels) {
    if (panel.engagementPanelSectionListRenderer) {
      const content = panel.engagementPanelSectionListRenderer.content;
      if (content.macroMarkersListRenderer) {
        contents = content.macroMarkersListRenderer.contents;
        break;
      }
    }
  }

  if (!contents) return;

  const areAutoGenerated = "macroMarkersInfoItemRenderer" in contents[0];
  contents = contents.slice(areAutoGenerated ? 1 : 0);

  contents.forEach((chapter: any) => {
    chapter = chapter.macroMarkersListItemRenderer;
    console.log(chapter);
    let timeStr = chapter.timeDescription.simpleText;
    const timeParts = timeStr.split(":").map(Number);

    let timeInt = 0;
    if (timeParts.length === 3) {
      timeInt = timeParts[0] * 3600 + timeParts[1] * 60 + timeParts[2];
    } else if (timeParts.length === 2) {
      timeInt = timeParts[0] * 60 + timeParts[1];
    } else if (timeParts.length === 1) {
      timeInt = timeParts[0];
    }

    chapters.push({
      title: chapter.title.simpleText,
      time: timeInt,
      thumbnails: chapter.thumbnail.thumbnails,
    });
  });
  return chapters;
};
